# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 264c1b334b16b66226db879f24e3d9d66607b0b0551aa4d47014f6c6c410e3100ee82f75c5064393dba1ac431e7d970f004b80c6ffc9ceb7e7356be57ca2d855

test:
  secret_key_base: 6147c1819c7698fcac411922d4b4d19f34a9a0312275c5682074b48cc9d1cdb61d2d08f406f0d9d163cc722709bac0d14c5c161f7618495567938266393b9849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
